CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` VARCHAR(20) PRIMARY KEY,
  `ADDRESS` VARCHAR(255),
  `PHONE` VARCHAR(30),
  `FIRST_NAME` VARCHAR(20),
  `SURNAME` VARCHAR(20),
  `EMAIL` VARCHAR(30),
  `PASSWORD` VARCHAR(20),
  `VIEW_COUNT` INT
);

CREATE TABLE `ADMIN_AND_STAFF` (
  `ACCOUNT_ID` VARCHAR(20) PRIMARY KEY,
  `NAME` VARCHAR(20),
  `PHONE` VARCHAR(30),
  `EMAIL` VARCHAR(30),
  `PASSWORD` VARCHAR(20)
);

CREATE TABLE `PACKAGE` (
  `PACKAGE_ID` VARCHAR(30) NOT NULL PRIMARY KEY ,
  `PACKAGE_NAME` VARCHAR(20),
  `PACKAGE_TYPE_ID` INT,
  `PITCH_TYPE_ID` INT,
  `LOCATION_ID` VARCHAR(20),
  `DURATION` INT,
  `PRICE` INT,
  `DESCRIPTION1` VARCHAR(255),
  `DESCRIPTION2` VARCHAR(255),
  `PICTURE1` VARCHAR(255),
  `PICTURE2` VARCHAR(255),
  `QUANTITY` VARCHAR(10),
  `STATUS` VARCHAR(10),
  `VIEW_COUNT` INT
);

CREATE TABLE `LOCATION` (
  `LOCATION_ID` VARCHAR(30) NOT NULL PRIMARY KEY ,
  `LOCATION_TYPE_ID` INT,
  `LOCATION_NAME` VARCHAR(20),
  `FULL_LOCATION` VARCHAR(255),
  `PICTURE` VARCHAR(255),
  `DESCRIPTION` VARCHAR(255)
);

CREATE TABLE `PACKAGE_TYPE` (
  `PACKAGE_TYPE_ID` VARCHAR(30) NOT NULL PRIMARY KEY ,
  `PACKAGE_TYPE_NAME` VARCHAR(20),
  `DESCRIPTION` VARCHAR(255),
  `PICTURE1` VARCHAR(255),
  `PICTURE2` VARCHAR(255)
);

CREATE TABLE `PITCH_TYPE` (
  `PITCH_TYPE_ID` VARCHAR(30) NOT NULL PRIMARY KEY ,
  `PITCH_TYPE_NAME` VARCHAR(20),
  `DESCRIPTION` VARCHAR(255),
  `PICTURE1` VARCHAR(255),
  `PICTURE2` VARCHAR(255)
);

CREATE TABLE `BOOKING` (
  `BOOKING_ID` VARCHAR(30) NOT NULL PRIMARY KEY,
  `CUSTOMER_ID` VARCHAR(20),
  `PACKAGE_ID` VARCHAR(20),
  `QUANTITY` INT,
  `TAX` INT,
  `PRICE` INT,
  `TOTAL_AMOUNT` INT
);

CREATE TABLE `LOCATION_TYPE` (
  `LOCATION_TYPE_ID` VARCHAR(30) NOT NULL PRIMARY KEY ,
  `LOCATION_TYPE_NAME` VARCHAR(20),
  `DESCRIPTION` VARCHAR(255)
);

ALTER TABLE `PACKAGE` ADD FOREIGN KEY (`PACKAGE_TYPE_ID`) REFERENCES `PACKAGE_TYPE` (`PACKAGE_TYPE_ID`);

ALTER TABLE `PACKAGE` ADD FOREIGN KEY (`PITCH_TYPE_ID`) REFERENCES `PITCH_TYPE` (`PITCH_TYPE_ID`);

ALTER TABLE `BOOKING` ADD FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`);

ALTER TABLE `BOOKING` ADD FOREIGN KEY (`PACKAGE_ID`) REFERENCES `PACKAGE` (`PACKAGE_ID`);

ALTER TABLE `PACKAGE` ADD FOREIGN KEY (`LOCATION_ID`) REFERENCES `LOCATION` (`LOCATION_ID`);

ALTER TABLE `LOCATION` ADD FOREIGN KEY (`LOCATION_TYPE_ID`) REFERENCES `LOCATION_TYPE` (`LOCATION_TYPE_ID`);
